# Font config:
[ font ]
    # Normal (roman):
    normal={ family= "CommitMono Nerd Font", style= "Regular" }

[keyboard]
   bindings = [{ key= "N",  mods= "Command", action= "SpawnNewInstance" }]

[general]
import = [
    "~/.config/alacritty/alacritty-theme/themes/catppuccin_macchiato.toml"
]
#[env]
#    term = "xterm-256color"
