import = [
    "~/.config/alacritty/alacritty-theme/themes/catppuccin_macchiato.toml"
]
# Font config:
[ font ]
    # Normal (roman):
    normal={ family= "CommitMono Nerd Font", style= "Regular" }

#[env]
#    term = "xterm-256color"
